Converted all Ava and Sinon testing to Jest
magiclabs/magic-admin-js pull request #83
Opened 2022-03-03 04:46 UTC by mushfichowdhury-magic

### 📦 Pull Request

Converting all Ava and Sinon code to Jest.

### ✅ Fixed Issues

- [List any fixed issues here like: Fixes #XXXX]

### 🚨 Test instructions

Everything should run with Jest on yarn test

### ⚠️ Don't forget to add a [semver](https://semver.org/) label!

- `patch`: Bug Fix?
- `minor`: New Feature?
- `major`: Breaking Change?
- `skip-release`: It's unnecessary to publish this change.

2022-03-03 16:16 UTC, smithki approved these changes

2022-03-03 16:19 UTC, smithki submitted a review, later dismissed

2022-03-03 16:19 UTC, smithki commented on src/index.ts
> +export { MagicAdminSDK } from './core/sdk';
Please revert this change! This would cause a breaking change to the public API!

2022-03-03 16:20 UTC, smithki requested changes
See comment above

2022-03-03 16:44 UTC, mushfichowdhury-magic commented
@smithki updated!

2022-03-03 16:51 UTC, smithki approved these changes

2022-03-03 16:51 UTC, merged

2022-03-29 19:11 UTC, smithki commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v1.4.0`](https://github.com/magiclabs/magic-admin-js/releases/tag/v1.4.0) :rocket: